# Basic provisioning example
- name: Ansible test
  hosts: localhost
  tasks:

    - name: launching AWS instance using Ansible
      amazon.aws.ec2_instance:
        name: instance_proof
        key_name: AnsibleMachine
        instance_type: t3.xlarge
        image_id: ami-0a32b54520652b8b1
        region: eu-north-1
        count: 1
        vpc_subnet_id: subnet-ebdc6090
        security_group: sg-007b3d7ae9debe853
        wait: yes
        state: running
        network:
          assign_public_ip: yes
      register: ec2_instance
      tags: create_ec2
    - name: Print Public IP Address
      debug:
        msg: "Public DNS name is {{ ec2_instance.instances[0].public_dns_name }}"
